CREATE TABLE IF NOT EXISTS MATCH(
  id BIGSERIAL PRIMARY KEY,
  description VARCHAR(255),
  match_date DATE NOT NULL,
  match_time TIME NOT NULL,
  team_a VARCHAR(64) NOT NULL,
  team_b VARCHAR(64) NOT NULL,
  sport SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS MATCH_ODDS(
    id BIGSERIAL PRIMARY KEY,
    match_id BIGINT NOT NULL
        CONSTRAINT match_odds_match_id_fkey
        REFERENCES MATCH(id) ON DELETE CASCADE,
    specifier VARCHAR(24) NOT NULL,
    ODD DOUBLE PRECISION NOT NULL
);



