CREATE TABLE IF NOT EXISTS MATCH(
  id BIGSERIAL PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  match_date DATE NOT NULL,
  match_time TIME NOT NULL,
  team_a VARCHAR(64) NOT NULL,
  team_b VARCHAR(64) NOT NULL,
  sport SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS MATCH_ODDS(
    id BIGSERIAL PRIMARY KEY,
    match_id BIGINT NOT NULL,
    specifier VARCHAR(24) NOT NULL,
    ODD NUMERIC(10,1) NOT NULL
);

ALTER TABLE MATCH_ODDS DROP CONSTRAINT IF EXISTS match_odds_match_id_fkey;
ALTER TABLE MATCH_ODDS ADD CONSTRAINT match_odds_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES MATCH(id);


